name: decksterity
version: '0.1.0'
category: Web
author: Louis Pilfold
maintainer: louis@lpil.uk
copyright: 2017 - Present Louis Pilfold
license: MPL-2.0
license-file: LICENCE
github: lpil/decksterity
extra-source-files:
- README.md

library:
  source-dirs: src
  exposed-modules:
  - Lib
  dependencies:
  - base >=4.7 && <5

executables:
  decksterity:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - decksterity

tests:
  decksterity-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - decksterity
    - hspec
