type track = {
  title: string,
  artist: option(string),
  album: option(string),
  bpm: option(int),
  number: option(int),
};

let track: list(track) = [
  {
    title: "Rip your nips off",
    artist: Some("Captain Credible"),
    album: Some("Fantasy Mansion"),
    bpm: Some(180),
    number: Some(1),
  },
  {
    title: "Rip your nips off",
    artist: Some("Captain Credible"),
    album: Some("Fantasy Mansion"),
    bpm: Some(180),
    number: Some(1),
  },
  {
    title: "Rip your nips off",
    artist: Some("Captain Credible"),
    album: Some("Fantasy Mansion"),
    bpm: Some(180),
    number: Some(1),
  },
  {
    title: "Rip your nips off",
    artist: Some("Captain Credible"),
    album: Some("Fantasy Mansion"),
    bpm: Some(180),
    number: Some(1),
  },
  {
    title: "Rip your nips off",
    artist: Some("Captain Credible"),
    album: Some("Fantasy Mansion"),
    bpm: Some(180),
    number: Some(1),
  },
  {
    title: "Rip your nips off",
    artist: Some("Captain Credible"),
    album: Some("Fantasy Mansion"),
    bpm: Some(180),
    number: Some(1),
  },
  {
    title: "Rip your nips off",
    artist: Some("Captain Credible"),
    album: Some("Fantasy Mansion"),
    bpm: Some(180),
    number: Some(1),
  },
  {
    title: "Rip your nips off",
    artist: Some("Captain Credible"),
    album: Some("Fantasy Mansion"),
    bpm: Some(180),
    number: Some(1),
  },
  {
    title: "Rip your nips off",
    artist: Some("Captain Credible"),
    album: Some("Fantasy Mansion"),
    bpm: Some(180),
    number: Some(1),
  },
  {
    title: "Rip your nips off",
    artist: Some("Captain Credible"),
    album: Some("Fantasy Mansion"),
    bpm: Some(180),
    number: Some(1),
  },
  {
    title: "Rip your nips off",
    artist: Some("Captain Credible"),
    album: Some("Fantasy Mansion"),
    bpm: Some(180),
    number: Some(1),
  },
  {
    title: "Rip your nips off",
    artist: Some("Captain Credible"),
    album: Some("Fantasy Mansion"),
    bpm: Some(180),
    number: Some(1),
  },
  {
    title: "Rip your nips off",
    artist: Some("Captain Credible"),
    album: Some("Fantasy Mansion"),
    bpm: Some(180),
    number: Some(1),
  },
  {
    title: "Rip your nips off",
    artist: Some("Captain Credible"),
    album: Some("Fantasy Mansion"),
    bpm: Some(180),
    number: Some(1),
  },
  {
    title: "Rip your nips off",
    artist: Some("Captain Credible"),
    album: Some("Fantasy Mansion"),
    bpm: Some(180),
    number: Some(1),
  },
  {
    title: "Rip your nips off",
    artist: Some("Captain Credible"),
    album: Some("Fantasy Mansion"),
    bpm: Some(180),
    number: Some(1),
  },
  {
    title: "Rip your nips off",
    artist: Some("Captain Credible"),
    album: Some("Fantasy Mansion"),
    bpm: Some(180),
    number: Some(1),
  },
  {
    title: "Rip your nips off",
    artist: Some("Captain Credible"),
    album: Some("Fantasy Mansion"),
    bpm: Some(180),
    number: Some(1),
  },
  {
    title: "Rip your nips off",
    artist: Some("Captain Credible"),
    album: Some("Fantasy Mansion"),
    bpm: Some(180),
    number: Some(1),
  },
  {
    title: "Rip your nips off",
    artist: Some("Captain Credible"),
    album: Some("Fantasy Mansion"),
    bpm: Some(180),
    number: Some(1),
  },
  {
    title: "Rip your nips off",
    artist: Some("Captain Credible"),
    album: Some("Fantasy Mansion"),
    bpm: Some(180),
    number: Some(1),
  },
  {
    title: "Rip your nips off",
    artist: Some("Captain Credible"),
    album: Some("Fantasy Mansion"),
    bpm: Some(180),
    number: Some(1),
  },
  {
    title: "Rip your nips off",
    artist: Some("Captain Credible"),
    album: Some("Fantasy Mansion"),
    bpm: Some(180),
    number: Some(1),
  },
  {
    title: "Rip your nips off",
    artist: Some("Captain Credible"),
    album: Some("Fantasy Mansion"),
    bpm: Some(180),
    number: Some(1),
  },
];
